// VerbenApp — Directorio de fiestas Galicia verano 2026
// 36 fiestas (rondas 1-3 de deep-research con verificación adversarial 2/3 votos).
// estadoFecha:
//   "confirmada" = cartel/fuente oficial 2026
//   "fija"       = día de santo/calendario (no cambia nunca)
//   "recurrente" = derivada de regla histórica estable (ej. "primer sábado de agosto")
// NOTA: San Froilán y O Grove caen en octubre (justo fuera de la ventana de verano,
//       incluidas por ser las más grandes de su categoría). Marcadas con "fueraVentana".

export type Provincia = "A Coruña" | "Lugo" | "Ourense" | "Pontevedra";
export type TipoFiesta = "concierto" | "gastronomica" | "tradicional" | "romeria";

export interface Review {
  autor: string;
  texto: string;
  año: number;
}

export interface Fiesta {
  id: string;
  nombre: string;
  pueblo: string;
  provincia: Provincia;
  fechaInicio: string; // YYYY-MM-DD
  fechaFin: string;    // YYYY-MM-DD
  estadoFecha: "confirmada" | "fija" | "recurrente";
  fueraVentana?: boolean;
  tipo: TipoFiesta;
  bandas: string[];
  comida: string[];
  atracciones: boolean;
  horaFin: string | null;   // null = sin dato verificado
  motivoEspecial: string | null;
  datoCurioso: string;
  interesTuristico: string | null;
  reviews: Review[];
  cobertura: number;   // 1-5, escala compartida con las fiestas parroquiales (estrella = 5)
}

export const fiestas: Fiesta[] = [
  // ───────────── A CORUÑA ─────────────
  {
    id: "san-xoan-coruna",
    nombre: "Noite de San Xoán de A Coruña",
    pueblo: "A Coruña",
    provincia: "A Coruña",
    fechaInicio: "2026-06-23",
    fechaFin: "2026-06-23",
    estadoFecha: "fija",
    tipo: "tradicional",
    bandas: [],
    comida: ["Sardiñada"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Noche de San Juan — hogueras y meigas",
    datoCurioso: "Fiesta de Interés Turístico Internacional. Las playas de Riazor y Orzán se llenan de hogueras (cacharelas) la noche más mágica del año. Zona piloto en Riazor con ~50 parcelas.",
    interesTuristico: "Internacional",
    reviews: [], cobertura: 5,
  },
  {
    id: "ortigueira-mundo-celta",
    nombre: "Festival Internacional do Mundo Celta de Ortigueira",
    pueblo: "Ortigueira",
    provincia: "A Coruña",
    fechaInicio: "2026-07-09",
    fechaFin: "2026-07-12",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: ["Xara (ganadora Concurso Runas 2025)"],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Música folk y celta — gratuito",
    datoCurioso: "Activo desde 1978. En 2025 reunió +110.000 personas en su 50 aniversario. El gran referente musical del verano gallego.",
    interesTuristico: "Internacional (2005)",
    reviews: [], cobertura: 5,
  },
  {
    id: "percebe-roncudo-corme",
    nombre: "Festa do Percebe do Roncudo",
    pueblo: "Corme (Ponteceso)",
    provincia: "A Coruña",
    fechaInicio: "2026-07-18",
    fechaFin: "2026-07-18",
    estadoFecha: "confirmada",
    tipo: "gastronomica",
    bandas: [],
    comida: ["Percebe do Roncudo"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Fiesta del Percebe — el 'oro negro' del Atlántico",
    datoCurioso: "XXXIV edición. En 2025 se sirvieron +900 kg de percebe recién sacado del mar en la Costa da Morte.",
    interesTuristico: "Sí",
    reviews: [], cobertura: 5,
  },
  {
    id: "apostolo-santiago",
    nombre: "Festas do Apóstolo Santiago / Día de Galicia",
    pueblo: "Santiago de Compostela",
    provincia: "A Coruña",
    fechaInicio: "2026-07-24",
    fechaFin: "2026-07-25",
    estadoFecha: "fija",
    tipo: "tradicional",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Fuegos del Apóstol (noche del 24) + Día Nacional de Galicia (25)",
    datoCurioso: "El espectáculo pirotécnico frente a la catedral reúne a +20.000 personas en la Praza do Obradoiro. Las festividades se extienden ~11 días.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },

  {
    id: "percebe-aguino",
    nombre: "Festa do Percebe de Aguiño",
    pueblo: "Aguiño (Ribeira)",
    provincia: "A Coruña",
    fechaInicio: "2026-07-26",
    fechaFin: "2026-07-26",
    estadoFecha: "fija",
    tipo: "gastronomica",
    bandas: [],
    comida: ["Percebe"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Fiesta del Percebe",
    datoCurioso: "Último domingo de julio. Celebrada desde 1997, llega a poner a la venta hasta una tonelada de percebe en la villa marinera de Aguiño, en O Barbanza.",
    interesTuristico: "De Galicia",
    reviews: [], cobertura: 5,
  },
  {
    id: "san-roque-globo-betanzos",
    nombre: "San Roque e Globo de Betanzos",
    pueblo: "Betanzos",
    provincia: "A Coruña",
    fechaInicio: "2026-08-16",
    fechaFin: "2026-08-16",
    estadoFecha: "fija",
    tipo: "tradicional",
    bandas: [],
    comida: [],
    atracciones: true,
    horaFin: null,
    motivoEspecial: "San Roque — el Globo de Betanzos",
    datoCurioso: "A medianoche se eleva el Globo de Betanzos, el globo de papel artesanal más grande del mundo. Fiesta de Interés Turístico.",
    interesTuristico: "Sí",
    reviews: [], cobertura: 5,
  },
  {
    id: "caneiros-betanzos",
    nombre: "Os Caneiros de Betanzos",
    pueblo: "Betanzos",
    provincia: "A Coruña",
    fechaInicio: "2026-08-18",
    fechaFin: "2026-08-25",
    estadoFecha: "fija",
    tipo: "romeria",
    bandas: [],
    comida: ["Empanada", "Vino"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Romería fluvial por el río Mandeo",
    datoCurioso: "Dos xiras (18 y 25 ago): se sube en barca por el Mandeo hasta el campo dos Caneiros, con empanada, vino y la 'batalla del vino'. Fuegos en la Ponte Vella a las 23h. Las fechas pueden moverse por el tiempo.",
    interesTuristico: "Sí",
    reviews: [], cobertura: 5,
  },

  {
    id: "son-do-camino",
    nombre: "O Son do Camiño",
    pueblo: "Santiago de Compostela",
    provincia: "A Coruña",
    fechaInicio: "2026-06-18",
    fechaFin: "2026-06-20",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: ["Linkin Park", "Katy Perry"],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "El gran festival de música de Galicia",
    datoCurioso: "En el Monte do Gozo, a las puertas de Santiago. El festival más grande de Galicia por aforo y cabezas de cartel internacionales.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "romaria-dos-castros",
    nombre: "Romaría dos Castros",
    pueblo: "A Coruña",
    provincia: "A Coruña",
    fechaInicio: "2026-07-17",
    fechaFin: "2026-07-19",
    estadoFecha: "confirmada",
    tipo: "romeria",
    bandas: [],
    comida: ["Comida campestre"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Romería de barrio en A Coruña",
    datoCurioso: "Una de las romerías de barrio con más solera de la ciudad, dentro del calendario de fiestas coruñesas del verano.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "noroeste-estrella-galicia",
    nombre: "Noroeste Estrella Galicia",
    pueblo: "A Coruña",
    provincia: "A Coruña",
    fechaInicio: "2026-08-05",
    fechaFin: "2026-08-08",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Festival de música pop-rock gratuito",
    datoCurioso: "Coincide con las Fiestas de María Pita. Conciertos gratis en plena ciudad de A Coruña.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "maria-pita",
    nombre: "Fiestas de María Pita",
    pueblo: "A Coruña",
    provincia: "A Coruña",
    fechaInicio: "2026-08-01",
    fechaFin: "2026-08-01",
    estadoFecha: "recurrente",
    tipo: "concierto",
    bandas: [],
    comida: [],
    atracciones: true,
    horaFin: null,
    motivoEspecial: "Las fiestas patronales de A Coruña",
    datoCurioso: "Todo el mes de agosto: conciertos, ferias, exposiciones y actividades por toda la ciudad en honor a la heroína María Pita.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },

  // ───────────── LUGO ─────────────
  {
    id: "arde-lucus",
    nombre: "Arde Lucus",
    pueblo: "Lugo",
    provincia: "Lugo",
    fechaInicio: "2026-06-18",
    fechaFin: "2026-06-21",
    estadoFecha: "confirmada",
    tipo: "tradicional",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Recreación histórica romana y castreña",
    datoCurioso: "25 aniversario en 2026 (nacida en 2002). Mercados, campamentos, batallas castreños vs. romanos y desfiles dentro de la muralla romana. La gran fiesta de Lugo.",
    interesTuristico: "Internacional (2023)",
    reviews: [], cobertura: 5,
  },
  {
    id: "san-froilan-lugo",
    nombre: "San Froilán",
    pueblo: "Lugo",
    provincia: "Lugo",
    fechaInicio: "2026-10-04",
    fechaFin: "2026-10-12",
    estadoFecha: "fija",
    fueraVentana: true,
    tipo: "gastronomica",
    bandas: [],
    comida: ["Pulpo á feira"],
    atracciones: true,
    horaFin: null,
    motivoEspecial: "Patrón San Froilán (día grande 5 oct) + feria medieval (12 oct)",
    datoCurioso: "Origen en feria de ganado del s. XIX. Sus casetas-pulperías de pulpo á feira son emblema. La gran fiesta de otoño de Lugo.",
    interesTuristico: "Nacional",
    reviews: [], cobertura: 5,
  },

  {
    id: "resurrection-fest",
    nombre: "Resurrection Fest",
    pueblo: "Viveiro",
    provincia: "Lugo",
    fechaInicio: "2026-07-01",
    fechaFin: "2026-07-04",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "El gran festival de metal y rock del norte",
    datoCurioso: "Uno de los festivales de metal más importantes de Europa. Convierte Viveiro (10.000 hab.) en peregrinación de decenas de miles de metaleros cada verano.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "rapa-candaoso",
    nombre: "Rapa das Bestas de Candaoso",
    pueblo: "Viveiro",
    provincia: "Lugo",
    fechaInicio: "2026-07-04",
    fechaFin: "2026-07-05",
    estadoFecha: "confirmada",
    tipo: "tradicional",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Curro de caballos salvajes",
    datoCurioso: "La rapa de la Mariña lucense: se baja a las bestas del monte para raparles las crines en el curro. Fiesta de Interés Turístico.",
    interesTuristico: "De Galicia",
    reviews: [], cobertura: 5,
  },
  {
    id: "bonito-burela",
    nombre: "Feira do Bonito de Burela",
    pueblo: "Burela",
    provincia: "Lugo",
    fechaInicio: "2026-08-01",
    fechaFin: "2026-08-01",
    estadoFecha: "recurrente",
    tipo: "gastronomica",
    bandas: [],
    comida: ["Bonito del norte"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Fiesta del Bonito",
    datoCurioso: "Primer sábado de agosto, +30 años seguidos. Interés Turístico Nacional (2019). Burela es el puerto bonitero de referencia de Galicia.",
    interesTuristico: "Nacional (2019)",
    reviews: [], cobertura: 5,
  },
  {
    id: "osa-do-mar",
    nombre: "Festival Osa do Mar",
    pueblo: "Burela",
    provincia: "Lugo",
    fechaInicio: "2026-09-04",
    fechaFin: "2026-09-06",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Festival indie / pop-rock",
    datoCurioso: "Cierra el verano musical de la Mariña lucense a principios de septiembre, frente al mar en Burela.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },

  // ───────────── OURENSE ─────────────
  {
    id: "fiestas-ourense",
    nombre: "Fiestas de Ourense",
    pueblo: "Ourense",
    provincia: "Ourense",
    fechaInicio: "2026-06-17",
    fechaFin: "2026-06-21",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: ["M-Clan (18 jun)", "Miguel Ríos (19 jun)", "Conductores Suicidas (20 jun)", "Hard GZ (20 jun)"],
    comida: [],
    atracciones: true,
    horaFin: null,
    motivoEspecial: "Fiestas urbanas de la capital",
    datoCurioso: "Mercado medieval en el Puente Romano, atracciones en el Parque Barbaña, hinchables acuáticos, espectáculo de drones (17 jun) y fuegos a medianoche del domingo 21.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "pulpo-carballino",
    nombre: "Festa do Pulpo de O Carballiño",
    pueblo: "O Carballiño",
    provincia: "Ourense",
    fechaInicio: "2026-08-09",
    fechaFin: "2026-08-09",
    estadoFecha: "confirmada",
    tipo: "gastronomica",
    bandas: [],
    comida: ["Pulpo á feira", "Pan de Cea", "Vinos del Ribeiro"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Fiesta del Pulpo",
    datoCurioso: "LXIV edición (fundada en 1962). Segundo domingo de agosto, en el Parque Municipal. La gran fiesta del pulpo de Ourense.",
    interesTuristico: "Sí",
    reviews: [], cobertura: 5,
  },

  {
    id: "festa-istoria-ribadavia",
    nombre: "Festa da Istoria de Ribadavia",
    pueblo: "Ribadavia",
    provincia: "Ourense",
    fechaInicio: "2026-08-28",
    fechaFin: "2026-08-30",
    estadoFecha: "confirmada",
    tipo: "tradicional",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Recreación histórica medieval",
    datoCurioso: "Ribadavia viaja a la Edad Media: se usa el 'maravedí' como moneda durante la fiesta, con bodas medievales, mercado y oficios de época. Interés Turístico Nacional (1997).",
    interesTuristico: "Nacional (1997)",
    reviews: [], cobertura: 5,
  },

  // ───────────── PONTEVEDRA ─────────────
  {
    id: "romaria-corpino",
    nombre: "Romaría do Corpiño",
    pueblo: "Lalín",
    provincia: "Pontevedra",
    fechaInicio: "2026-06-23",
    fechaFin: "2026-06-24",
    estadoFecha: "fija",
    tipo: "romeria",
    bandas: [],
    comida: ["Pulpo", "Empanada"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Romería sanadora en el santuario do Corpiño",
    datoCurioso: "Famosa por los 'endemoniados': se cree que la Virgen do Corpiño cura males y espíritus. Una de las romerías más singulares de Galicia. Fiesta de Interés Turístico.",
    interesTuristico: "De Galicia",
    reviews: [], cobertura: 5,
  },
  {
    id: "portamerica",
    nombre: "PortAmérica",
    pueblo: "Caldas de Reis",
    provincia: "Pontevedra",
    fechaInicio: "2026-07-09",
    fechaFin: "2026-07-11",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: [],
    comida: ["Gastronomía de autor"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Festival de música + gastronomía",
    datoCurioso: "Mezcla conciertos con cocina de cobertura Michelin entre los pinos del recinto de Caldas de Reis. Música y buen comer a partes iguales.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "atlantic-fest",
    nombre: "Atlantic Fest",
    pueblo: "Vilagarcía de Arousa",
    provincia: "Pontevedra",
    fechaInicio: "2026-07-17",
    fechaFin: "2026-07-19",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Festival indie frente a la ría",
    datoCurioso: "Tres días de indie y pop en la Plaza de Galicia de Vilagarcía, con la ría de Arousa de fondo.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "sinsal-san-simon",
    nombre: "Sinsal SON Estrella Galicia",
    pueblo: "Illa de San Simón (Redondela)",
    provincia: "Pontevedra",
    fechaInicio: "2026-07-24",
    fechaFin: "2026-07-26",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Festival en una isla, con cartel secreto",
    datoCurioso: "Se celebra en la isla de San Simón, en plena ría de Vigo. El cartel es SECRETO: compras la entrada sin saber quién toca. Aforo limitadísimo.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "santa-marta-ribarteme",
    nombre: "Romaría de Santa Marta de Ribarteme",
    pueblo: "As Neves",
    provincia: "Pontevedra",
    fechaInicio: "2026-07-29",
    fechaFin: "2026-07-29",
    estadoFecha: "fija",
    tipo: "romeria",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "La romería de los ataúdes",
    datoCurioso: "La fiesta más sobrecogedora de Galicia: quienes han estado al borde de la muerte y se salvaron desfilan DENTRO de un ataúd, cargados por sus familiares, para dar gracias a Santa Marta. Fiesta de Interés Turístico.",
    interesTuristico: "De Galicia",
    reviews: [], cobertura: 5,
  },
  {
    id: "sonrias-baixas",
    nombre: "SonRías Baixas",
    pueblo: "Bueu",
    provincia: "Pontevedra",
    fechaInicio: "2026-07-30",
    fechaFin: "2026-08-01",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Festival de rap, reggae y mestizaje",
    datoCurioso: "Tres días de música mestiza junto al mar en Bueu. Referente del hip-hop y el reggae en Galicia.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "romeria-vikinga-catoira",
    nombre: "Romería Vikinga de Catoira",
    pueblo: "Catoira",
    provincia: "Pontevedra",
    fechaInicio: "2026-08-02",
    fechaFin: "2026-08-02",
    estadoFecha: "recurrente",
    tipo: "tradicional",
    bandas: [],
    comida: ["Mejillón", "Vino"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Recreación del desembarco vikingo",
    datoCurioso: "Primer domingo de agosto. Drakkars vikingos asaltan las Torres de Oeste y hay batalla con vino y mejillones. Fiesta de Interés Turístico Internacional, desde 1960.",
    interesTuristico: "Internacional",
    reviews: [], cobertura: 5,
  },
  {
    id: "mexillon-vilanova",
    nombre: "Festa do Mexillón e do Berberecho",
    pueblo: "Vilanova de Arousa",
    provincia: "Pontevedra",
    fechaInicio: "2026-08-07",
    fechaFin: "2026-08-10",
    estadoFecha: "recurrente",
    tipo: "gastronomica",
    bandas: [],
    comida: ["Mejillón", "Berberecho"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Fiesta del Mejillón y el Berberecho",
    datoCurioso: "Principios de agosto en la cuna del mejillón gallego, la ría de Arousa. Fiesta de Interés Turístico de Galicia. (Fechas orientativas hasta cartel 2026.)",
    interesTuristico: "De Galicia",
    reviews: [], cobertura: 5,
  },
  {
    id: "peregrina-pontevedra",
    nombre: "Festas da Peregrina",
    pueblo: "Pontevedra",
    provincia: "Pontevedra",
    fechaInicio: "2026-08-08",
    fechaFin: "2026-08-18",
    estadoFecha: "recurrente",
    tipo: "tradicional",
    bandas: [],
    comida: [],
    atracciones: true,
    horaFin: null,
    motivoEspecial: "Fiestas patronales de Pontevedra (Virxe Peregrina)",
    datoCurioso: "Diez días de fiesta en honor a la Virxe Peregrina, patrona de la provincia. Conciertos, feria y el casco viejo de Pontevedra a tope.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "festa-auga-vilagarcia",
    nombre: "Festa da Auga de Vilagarcía",
    pueblo: "Vilagarcía de Arousa",
    provincia: "Pontevedra",
    fechaInicio: "2026-08-16",
    fechaFin: "2026-08-16",
    estadoFecha: "fija",
    tipo: "tradicional",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "San Roque — la batalla del agua",
    datoCurioso: "El día de San Roque, hasta 30.000 personas se empapan unas a otras con agua de cubos, mangueras y camiones cisterna en la Praza de Galicia. Fiesta de Interés Turístico Nacional.",
    interesTuristico: "Nacional",
    reviews: [], cobertura: 5,
  },
  {
    id: "langosta-a-guarda",
    nombre: "Festa da Langosta e da Cociña Mariñeira",
    pueblo: "A Guarda",
    provincia: "Pontevedra",
    fechaInicio: "2026-07-03",
    fechaFin: "2026-07-05",
    estadoFecha: "confirmada",
    tipo: "gastronomica",
    bandas: [],
    comida: ["Langosta", "Cocina marinera"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Fiesta de la Langosta",
    datoCurioso: "XXXIV edición. La carpa abre el viernes a las 12:00 en la villa marinera de A Guarda, en la desembocadura del Miño.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "rapa-bestas-sabucedo",
    nombre: "A Rapa das Bestas de Sabucedo",
    pueblo: "Sabucedo (A Estrada)",
    provincia: "Pontevedra",
    fechaInicio: "2026-07-03",
    fechaFin: "2026-07-06",
    estadoFecha: "confirmada",
    tipo: "tradicional",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Curro de caballos salvajes bajo el patronazgo de San Lorenzo",
    datoCurioso: "Único curro de Galicia donde los aloitadores se enfrentan a los caballos a mano limpia, sin cuerdas ni palos. +400 años de historia; reúne a +20.000 personas en una aldea de menos de 60 habitantes.",
    interesTuristico: "Internacional (2007) · Bien de Interés Cultural (2025)",
    reviews: [], cobertura: 5,
  },
  {
    id: "san-benitino-lerez",
    nombre: "Romería de San Benitiño de Lérez",
    pueblo: "Lérez (Pontevedra)",
    provincia: "Pontevedra",
    fechaInicio: "2026-07-11",
    fechaFin: "2026-07-11",
    estadoFecha: "fija",
    tipo: "romeria",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Día de San Benito",
    datoCurioso: "Celebrada desde 1929 en el monasterio de San Salvador de Lérez. Tiene dos citas al año: 21 de marzo y 11 de julio.",
    interesTuristico: "De Galicia",
    reviews: [], cobertura: 5,
  },
  {
    id: "albarino-cambados",
    nombre: "Festa do Albariño de Cambados",
    pueblo: "Cambados",
    provincia: "Pontevedra",
    fechaInicio: "2026-07-29",
    fechaFin: "2026-08-02",
    estadoFecha: "confirmada",
    tipo: "gastronomica",
    bandas: [],
    comida: ["Vino albariño", "Marisco"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Fiesta del Vino Albariño",
    datoCurioso: "LXXIV edición — una de las fiestas gastronómicas más antiguas de Galicia. Cerca de medio centenar de bodegas en el Paseo da Calzada.",
    interesTuristico: "Nacional (1977)",
    reviews: [], cobertura: 5,
  },
  {
    id: "marisquino-vigo",
    nombre: "O Marisquiño",
    pueblo: "Vigo",
    provincia: "Pontevedra",
    fechaInicio: "2026-08-06",
    fechaFin: "2026-08-09",
    estadoFecha: "confirmada",
    tipo: "concierto",
    bandas: [],
    comida: [],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Cultura urbana, deportes de acción y conciertos",
    datoCurioso: "XXVI edición. Dos enclaves: playa de Samil (deporte, música, arte urbano frente a las Cíes) y descenso urbano en MTB desde la Fortaleza de O Castro por el Casco Vello.",
    interesTuristico: null,
    reviews: [], cobertura: 5,
  },
  {
    id: "marisco-o-grove",
    nombre: "Festa do Marisco de O Grove",
    pueblo: "O Grove",
    provincia: "Pontevedra",
    fechaInicio: "2026-10-01",
    fechaFin: "2026-10-01",
    estadoFecha: "confirmada",
    fueraVentana: true,
    tipo: "gastronomica",
    bandas: [],
    comida: ["Marisco"],
    atracciones: false,
    horaFin: null,
    motivoEspecial: "Fiesta del Marisco",
    datoCurioso: "63 edición (desde 1963). 12 días de marisco en la península de O Grove. La gran fiesta del marisco de Galicia.",
    interesTuristico: "Internacional",
    reviews: [], cobertura: 5,
  },
];
